update chart with prod image for jpm
toggleglobal/workflows pull request #66
Opened 2023-07-17 16:43 UTC by ali-tog

2023-07-17 16:44 UTC, ali-tog commented on .github/workflows/image-web-app.yml
> +          cmd: yq -i '.common.image.tag = strenv(env.SHORT_SHA)' ./charts/wui-jpm/values.yaml
@luisprates i am assuming `cd apps-infrastructure` not required since it has been done above but not sure if we need to do it again?

2023-07-17 17:08 UTC, luisprates requested changes

2023-07-17 17:08 UTC, luisprates commented on .github/workflows/image-web-app.yml
> +          cmd: yq -i '.common.image.tag = strenv(env.SHORT_SHA)' ./charts/wui-jpm/values.yaml
Each step is executed from the root directory you need to include the cd apps infra command

2023-07-18 09:43 UTC, luisprates approved these changes

2023-07-18 10:27 UTC, merged